---
title: "Analysis of the trends that lead to the survival & downfall of American public libraries"
author: "Elizabeth Edminster & Sara Evans"
date: "2024-05-01"
output: pdf_document
---

```{r include=FALSE}
# libraries to load here
library(NbClust)
library(mclust)
library(flexclust)
library(cluster)
library(fpc)
library(knitr)
library(rattle)
library(dplyr)
library(stats)
library(factoextra)
library(ggplot2)

```

## 1.0 Introduction

#### 1.1 Project Description

This project aims to critically analyze data within the domain of public policy and business strategies, with a focus on NGOs, particularly public libraries. 

We aim to address various questions through our analysis such as, what quantifiable library traits are correlated with a library's long-term success and which traits commonly contribute to the demise of a library?  We consider it crucial to identify quantifiable traits associated with library success as strategies can be developed based on these factors to help libraries to better serve their communities, while also acknowledging the factors that impact a library's declining state. Moreover, we aim to explore whether library characteristics vary based on geographical location and city population, along with examining the evolution of libraries from 2011 to 2021. It's necessary to address these questions understand how libraries are distributed across different regions and whether all regions have equal access to a library. Additionally, tracking how libraries have evolved over the course of a decade will provide insights on how their community's needs have changed, as well as the popularity of libraries in general.

A library's success will be based on a combination of factors such as total inventory books, including physical books, e-books, and audio books, as this demonstrates a library's ability to provide resources to their community. In addition, the total number of visits a library receives each year will also determine success as a large number of visits indicates popularity among it's audience.
 
 
#### 1.2 Background
 
 




## 2.0 Data Description 

Data: https://www.imls.gov/research-evaluation/data-collection/publiclibraries-survey
This data is from the Institute of Museum & Library Services. They have data on these libraries nationally
from 2006 to 2021. The selected columns for our preliminary exploration are listed below. Further columns
& information about the data can be found at the provided link. 

The following columns are the variables selected for this project: (NOTE) The variables considered for analysis in this data have changed slightly from 2006-2021.The following variables are the variables taken from 2021. If a given variable does not exist in prior years, it will not be considered, but no extra previously removed columns will be added.

LIBID - Identifier: Library identification code assigned by the state. IMLS assigns the FSCSKEY to this field if the state did not assign a code./
LIBNAME - Identifier: Name of library (administrative entity)/
STABR - Identifier: Two-letter American National Standards Institute (ANSI) State Code. (See Appendix D for list of State Codes.)/
C_LEGBAS - Categorical: Legal Basis Code CC–City/County CI–Municipal Government (city, town, or village) CO–County/Parish LD–Library District MJ–Multi-jurisdictional NL–Native American Tribal Government NP–Non-profit Association or Agency SD–School District OT–Other/
POPU_LSA - Numeric: Population of the Legal Service Area -1–Missing -3–Temporarily closed administrative entity -9–Data suppressed for analytic purposes/
VISITS - Numeric: This is the total number of persons entering the library for whatever purpose during the year./
BKVOL - Numeric: Books in print. Books are non-serial printed publications (including music scores or other bound forms of printed music, and maps) that are bound in hard or soft covers, or in loose-leaf format. Does not include unbound sheet music. Includes non-serial government documents. Including duplicates./
EBOOK - Numeric: E-books are digital documents (including those digitized by the library), licensed or not, where searchable text is prevalent, and which can be seen in analogy to a printed book (monograph).E-books are loaned to users on portable devices (e-book readers) or by transmitting the contents to the user’s 1 personal computer for a limited time. Includes ebooks held locally and remote e-books for which permanent or temporary access rights have been acquired. Including duplicates./
CAPITAL - Numeric: Report major capital expenditures (the acquisition of or additions to fixed assets)Examples include expenditures for (a) site acquisitions; (b) new buildings; (c) additions to or renovation of library buildings; (d) furnishings, equipment, and initial book stock for new buildings, building additions, or building renovations; (e) library automation systems; (f) new vehicles; and (g) other one-time major projects. Includes federal, state, local, or other revenue used for major capital expenditures. Only funds that are supported by expenditure documents (e.g., invoices, contracts, payroll records, etc.) at the point of disbursement should be included. Estimated costs are not included. Excludes expenditures for replacement and repair of existing furnishings and equipment, regular purchase of library materials, and investments for capital appreciation./
PRMATEXP - Numeric: Report all operating expenditures for the following print materials: books, current serial subscriptions, government documents, and any other print acquisitions.
ELMATEXP - Numeric: Report all operating expenditures for electronic (digital) materials. Types of electronic materials include e-books, audio and video downloadables, e-serials (including journals), government documents, databases (including locally mounted, full text or not), electronic files, reference tools, scores, maps, or pictures in electronic or digital format, including materials digitized by the library/
STAFFEXP - Numeric: This is the sum of Salaries & Wages Expenditures and Employee Benefits Expenditures/
STATNAME - Categorical: Name Change Code 00–No change from last year 06–Official name change 14– Minor name change/
LOCALE_MOD - Categorical: Urban-centric locale code. The geographic location in terms of the size of the community in which it is located and the proximity of that community to urban and metropolitan areas. Assigned based on the modal locale code of associated stationary outlets (i.e., central and branch libraries). 11–City, Large: Territory inside an urbanized area and inside a principal city with population of 250,000 or more. 12–City, Mid-size: Territory inside an urbanized area and inside a principal city with a population less than 250,000 and greater than or equal to 100,000. 13–City, Small: Territory inside an urbanized area and inside a principal city with a population less than 100,000. 21–Suburb, Large: Territory outside a principal city and inside an urbanized area with population of 250,000 or more. 22–Suburb, Mid-size: Territory outside a principal city and inside an urbanized area with a population less than 250,000 and greater than or equal to 100,000. 23–Suburb, Small: Territory outside a principal city and inside an urbanized area with a population less than 100,000. 31–Town, Fringe: Territory inside an urban cluster that is less than or equal to 10 miles from an urbanized area. 32–Town, Distant: Territory inside an urban cluster that is more than 10 miles and less than or equal to 35 miles from an urbanized area. 33–Town, Remote: Territory inside an urban cluster that is more than 35 miles from an urbanized area. 41–Rural, Fringe: Census-defined rural territory that is less than or equal to 5 miles from an urbanized area, as well as rural territory that is less than or equal to 2.5 miles from an urban cluster. 42–Rural, Distant: Census-defined rural territory that is more than 5 miles but less than or equal to 25 miles from an urbanized area, as well as rural territory that is more than 2.5 miles but less than or equal to 10 miles from an urban cluster./
WEBVISIT - Numeric: Total visits (sessions) to library website -1–Missing -3–Temporarily closed administrative entity -4–Not applicable/
WIFISESS - Numeric: Total annual wireless sessions provided by the library wireless service -1–Missing -3–Temporarily closed administrative entity/
PITUSR - Numeric: Uses of public Internet computers per year -1–Missing -3–Temporarily closed administrative entity/
LOANTO - Numeric: Total annual loans provided to other libraries -1–Missing -3–Temporarily closed administrative entity/
LOANFM - Numeric: Total annual loans received from other libraries -1–Missing -3–Temporarily closed administrative entity/





## 3.0 Analysis 

#### 3.1 Clustering

This statistical technique included K-Means clustering and model-based clustering. For the K-Means and model-based clusterings, the following variables were used: OBEREG, LIBRARIA, BKVOL, EBOOK, Total_Audio_Books, Total_Videos, REGBOR, and VISITS. The variable Total_Audio_Books was calculated using the AUDIO_PH and AUDIO_DL and the variable Total_Video was calculated using the VIDEOS_PH and AUDIO_DL.




#### 3.1.1 Clustering Results




#### 3.2 




#### 3.2.1 





## 4.0 Conclusions

## 5.0 References 
